### ISSUE TITLE
HW1 - úkol ke kontrole

### ISSUE THREAD

**Issue by Alkiono** [Alkiono/python_ds_2023#1]
Ahoj Marti, 
mohla by ses prosím podívat na úkol, jakmile budeš moct?

Děkuji moc.
Eva

**Comment by mcvincekova** [comment]
Ahoj @Alkiono 

Velmi pekne spracovane, tesi ma, ze si sa pohrala aj s bonusmi.

- myslim si, ze zakladne koncepty lin. regresie si aplikovala s prehladom
- ocenujem, ze notebook je rozumne strukturovany a svoje pozorovania / vysledky si aj okomentovala v markdown bunkach


Celkovo hodnotim ulohu za zvladnutu, co mozem odporucit do buducna:

Skus si data zobrazit, pre ucely linearnej regresie si napr. mozes vyskusat, ci uvidis nejaky vztah medzi `Y` a nejakymi indikatormi, napr. `FL` (kedze tu vidime silnu korelaciu)
![image](https://github.com/Alkiono/python_ds_2023/assets/44243029/bca24feb-a8e4-4582-9774-301575171ef1)

Taketo drobnosti ti mozu ukazat, ci skutocne mozes medzi premennymi predpokladat linearny vztah a ci uvidis nejake odlahle pozorovania (ktore mozu tvoj model ovplyvnit).
